SELECT  "borough",
        "block",
        "lot",
        "census tract 2010" AS "census_tract", 
        "cb2010" AS "census_block",
        "address",
        "zonedist1" AS "zone_dist_1",
        "zonedist2" AS "zone_dist_2",
        "zonedist3" AS "zone_dist_3",
        "zonedist4" AS "zone_dist_4",
        "overlay1" AS "comm_overlay_1"
        "overlay2" AS "comm_overlay_2"
        "ltdheight" AS "limited_height_district",
        "splitzone" AS "split_zoning",
        "bldgclass" AS "building_class",
        "landuse" AS "land_use",
        "easements" AS "num_easements",
        "ownertype" AS "owner_type",
        "ownername" AS "owner_name",
        "lotarea" AS "lot_area",
        "bldgarea" AS "area_building",
        "comarea" AS "area_floor_comm",
        "resarea" AS "area_floor_resi",
        "officearea" AS "area_floor_office",
        "retailarea" AS "area_floor_retail",
        "garagearea" AS "area_floor_garage",
        "strgearea" AS "area_floor_storage",
        "factryarea" AS "area_floor_factory",
        "otherarea" AS "area_floor_other",
        "areasource" AS "code_source_building_area",
        "numbldgs" AS "num_buildings",
        "numfloors" AS "num_floors",
        "unitsres" AS "num_units_resi",
        "unitstotal" AS "num_units_total",
        "lotfront" AS "lot_frontage",
        "lotdepth" AS "lot_depth",
        "bldgfront" AS "building_frontage",
        "bldgdepth" AS "building_depth",
        "proxcode" AS "code_proximity",
        "irrlotcode" AS "lot_irregular",
        "lottype" AS ""
        "bsmtcode",
        "assessland",
        "assesstot",
        "exempttot",
        "yearbuilt",
        "yearalter1",
        "yearalter2",
        "histdist",
        "landmark",
        "builtfar",
        "residfar",
        "commfar",
        "facilfar",
        "borocode",
        "bbl",
        "condono",
        "tract2010",
        "xcoord",
        "ycoord",
        "latitude",
        "longitude",
        "zonemap",
        "zmcode",
        "sanborn",
        "taxmap",
        "edesignum",
        "appbbl",
        "appdate",
        "plutomapid",
        "version",
        "sanitdistrict",
        "healthcenterdistrict",
        "firm07_flag",
        "pfirm15_flag",
        "rpaddate",
        "dcasdate",
        "zoningdate",
        "landmkdate",
        "basempdate",
        "masdate",
        "polidate",
        "edesigdate",
        "geom",
        "dcpedited",
        "notes"
FROM "pluto"."pluto" limit 10;